const PORT = process.env.PORT;
const MONGODB_URI = process.env.MONGODB;
const SMPT_EMAIL = process.env.SENDER_EMAIL;
const SMPT_PASSWORD = process.env.EMAIL_PASSWORD;
const SMPT_PORT = process.env.SMPT_PORT;
const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
export default {
  PORT,
  MONGODB_URI,
  SMPT_EMAIL,
  SMPT_PASSWORD,
  SMPT_PORT,
  JWT_SECRET_KEY,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
};
